# {{cookiecutter.project_slug}}/config.yml
model:
  name: {{cookiecutter.openai_model_name}}
  temperature: 0.7
  max_tokens: 1000

prompts:
  default_system_prompt: "You are a helpful AI assistant."